	<meta charset="utf-8">
	<title><?php echo $this->getTitle() ?></title>
	<meta name="description" content="<?php echo htmlspecialchars($this->getDescription()) ?>" />
	<meta name="keywords" content="<?php echo htmlspecialchars($this->getKeywords()) ?>" />
	<meta name="robots" content="<?php echo htmlspecialchars($this->getRobots()) ?>" />
	<link rel="icon" href="<?php echo $this->getFaviconFile(); ?>" type="image/x-icon" />
	<link rel="shortcut icon" href="<?php echo $this->getFaviconFile(); ?>" type="image/x-icon" />
	<?php echo $this->getChildHtml() ?>
	<?php $currentUrl = Mage::helper('core/url')->getCurrentUrl();$bodytag = str_replace("/amp/", "/", $currentUrl); ?>
	
	<link rel="canonical" href="<?php echo $bodytag; ?>" />
	