<amp-user-notification layout=nodisplay id="amp-user-notification1">
	<?php echo __('We have loaded the mobile fast version for you. You will not be able to purchase anything on this site, we will take you to our main site (which may take a little longer to load) when you click a purchase button or click "Shop on Full Site" in the header.');?>
	<button on="tap:amp-user-notification1.dismiss"><?php echo __('I accept'); ?></button>
</amp-user-notification>
